namespace IKPhones.Core.Entities;

public class TradeInLead
{
    public Guid Id { get; set; }
    
    public required string CustomerName { get; set; }
    public required string CustomerEmail { get; set; }
    public required string CustomerPhone { get; set; }

    // Link directly to the mathematical quote generated by your ValuationEngine
    public Guid DeviceValuationId { get; set; }
    public DeviceValuation? Valuation { get; set; }

    // Store the agreed-upon quote and the date they plan to visit the Akure store
    public decimal QuotedValue { get; set; }
    public DateTime InspectionDateUtc { get; set; }
    
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
}