// <auto-generated />
using System;
using System.Collections.Generic;
using IKPhones.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IKPhones.Infrastructure.Migrations
{
    [DbContext(typeof(IKPhonesDbContext))]
    [Migration("20260612175202_AddImageUrlToVariant")]
    partial class AddImageUrlToVariant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IKPhones.Core.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("IKPhones.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("IKPhones.Core.Entities.DeviceFamily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("DeviceFamilies");
                });

            modelBuilder.Entity("IKPhones.Core.Entities.DeviceValuation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeInMonths")
                        .HasColumnType("integer");

                    b.Property<string>("BodyCondition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("CalculatedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FinalApprovedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<List<string>>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsApprovedByAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ScreenCondition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("DeviceValuations");
                });

            modelBuilder.Entity("IKPhones.Core.Entities.DeviceVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("DeviceFamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageCapacity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceFamilyId");

                    b.ToTable("DeviceVariants");
                });

            modelBuilder.Entity("IKPhones.Core.Entities.InventoryUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionGrade")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("DeviceVariantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReservedBySessionId")
                        .HasColumnType("text");

                    b.Property<string>("RetailState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceVariantId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("InventoryUnits");
                });

            modelBuilder.Entity("IKPhones.Core.Entities.ValuationFormulaConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MarketDemandFactor")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("MonthlyDepreciationMultiplier")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.ToTable("ValuationFormulaConfigs");
                });

            modelBuilder.Entity("IKPhones.Core.Entities.DeviceFamily", b =>
                {
                    b.HasOne("IKPhones.Core.Entities.Brand", "Brand")
                        .WithMany("DeviceFamilies")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IKPhones.Core.Entities.Category", "Category")
                        .WithMany("DeviceFamilies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IKPhones.Core.Entities.DeviceVariant", b =>
                {
                    b.HasOne("IKPhones.Core.Entities.DeviceFamily", "DeviceFamily")
                        .WithMany("Variants")
                        .HasForeignKey("DeviceFamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceFamily");
                });

            modelBuilder.Entity("IKPhones.Core.Entities.InventoryUnit", b =>
                {
                    b.HasOne("IKPhones.Core.Entities.DeviceVariant", "Variant")
                        .WithMany("InventoryUnits")
                        .HasForeignKey("DeviceVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("IKPhones.Core.Entities.Brand", b =>
                {
                    b.Navigation("DeviceFamilies");
                });

            modelBuilder.Entity("IKPhones.Core.Entities.Category", b =>
                {
                    b.Navigation("DeviceFamilies");
                });

            modelBuilder.Entity("IKPhones.Core.Entities.DeviceFamily", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("IKPhones.Core.Entities.DeviceVariant", b =>
                {
                    b.Navigation("InventoryUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
